"""
Test suite for LLM-Free Local Knowledge AI Assistant
"""
import time
import logging
from backend.agents.conversational_code_assistant import ConversationalCodeAssistant

logging.basicConfig(level=logging.INFO)

PROMPT_TEST_QUESTIONS = [
    ("What is phone?", True),
    ("What is SQL Injection?", False),
    ("Why is eval() dangerous?", False),
    ("What is PEP 8?", False),
    ("What is AST analysis?", False),
    ("How do I fix hardcoded credentials?", False),
    ("What is football?", True),
]

EXPECTED_UNSUPPORTED_ANSWER = (
    "I can only answer questions related to SentinelAI's secure coding knowledge, "
    "including OWASP Top 10, PEP 8, AST analysis, security vulnerabilities, code analysis, and remediation rules."
)


def run_tests():
    assistant = ConversationalCodeAssistant()
    print("\n========================================================")
    print("RUNNING SENTINELAI AI ASSISTANT OFFLINE KNOWLEDGE TESTS")
    print("========================================================\n")

    total_time = 0.0

    # Mock findings to ensure unsupported questions DO NOT trigger finding context
    mock_findings = [
        {"line": 14, "severity": "Critical", "issue": "Hardcoded Password", "explanation": "Exposed key in variable"}
    ]

    for i, (q, is_unsupported) in enumerate(PROMPT_TEST_QUESTIONS, start=1):
        start = time.perf_counter()
        res = assistant.ask(question=q, optional_findings=mock_findings)
        elapsed = time.perf_counter() - start
        total_time += elapsed

        print(f"[{i}/7] Question: '{q}'")
        print(f"      Completed in: {elapsed:.5f}s (< 1s target: PASSED)")
        print(f"      Generated By: {res.get('generated_by')}")
        print(f"      Source:       {res.get('source')}")
        print(f"      Answer Snippet:")
        print(f"      {res.get('answer', '')[:140]}...\n")

        assert elapsed < 1.0, f"Question '{q}' took longer than 1 second: {elapsed}s"
        assert res.get("generated_by") == "local_knowledge_engine"
        assert res.get("source") == "local_knowledge"

        if is_unsupported:
            assert res.get("answer") == EXPECTED_UNSUPPORTED_ANSWER, (
                f"Mismatch for unsupported question '{q}'. Got: {res.get('answer')}"
            )
            assert "Hardcoded Password" not in res.get("answer"), (
                f"Finding context illegally attached to unsupported question '{q}'!"
            )
        else:
            assert res.get("answer") != EXPECTED_UNSUPPORTED_ANSWER, (
                f"Valid domain question '{q}' was mistakenly rejected as unsupported!"
            )

    print("========================================================")
    print(f"ALL 7 TESTS PASSED SUCCESSFULLY IN {total_time:.5f}s TOTAL!")
    print(f"AVERAGE LATENCY PER QUESTION: {total_time/len(PROMPT_TEST_QUESTIONS):.5f}s")
    print("========================================================\n")

if __name__ == "__main__":
    run_tests()
