"""
FastAPI Endpoint Validation Suite for SentinelAI Local Knowledge AI Assistant
"""
import time
from fastapi.testclient import TestClient
from backend.main import app

client = TestClient(app)

def test_chat_endpoint():
    print("\n--- TEST 1: POST /chat ---")
    start = time.perf_counter()
    response = client.post("/chat", json={"question": "What is SQL Injection?"})
    elapsed = time.perf_counter() - start

    assert response.status_code == 200, f"Expected 200, got {response.status_code}"
    data = response.json()
    print(f"Response status: {response.status_code}")
    print(f"Execution time:  {elapsed:.5f}s")
    print(f"Generated By:    {data.get('generated_by')}")
    print(f"Model:           {data.get('model')}")
    print(f"Sources:         {data.get('sources')}")
    print(f"Related Topics:  {data.get('related_topics')}")
    assert data.get("generated_by") == "local_knowledge_engine"
    assert "OWASP A03" in data.get("answer", "")
    print("[PASSED] POST /chat Passed!")

def test_explain_finding_endpoint():
    print("\n--- TEST 2: POST /explain-finding ---")
    start = time.perf_counter()
    finding_payload = {
        "finding": {
            "agent": "SecurityAgent",
            "severity": "Critical",
            "issue": "SQL Injection Vulnerability",
            "explanation": "SQL query concatenated on line 14.",
            "line": 14
        }
    }
    response = client.post("/explain-finding", json=finding_payload)
    elapsed = time.perf_counter() - start

    assert response.status_code == 200
    data = response.json()
    print(f"Response status: {response.status_code}")
    print(f"Execution time:  {elapsed:.5f}s")
    print(f"Status:          {data.get('status')}")
    print(f"Answer snippet:  {data.get('answer', '')[:100]}...")
    assert data.get("status") == "success"
    assert "Line 14" in data.get("answer", "")
    print("[PASSED] POST /explain-finding Passed!")

def test_ask_remediation_endpoint():
    print("\n--- TEST 3: POST /ask-remediation ---")
    start = time.perf_counter()
    finding_payload = {
        "finding": {
            "agent": "SecurityAgent",
            "severity": "Critical",
            "issue": "SQL Injection Vulnerability",
            "explanation": "SQL query concatenated on line 14.",
            "line": 14
        },
        "code": "cursor.execute('SELECT * FROM users WHERE name = ' + name)"
    }
    response = client.post("/ask-remediation", json=finding_payload)
    elapsed = time.perf_counter() - start

    assert response.status_code == 200
    data = response.json()
    print(f"Response status: {response.status_code}")
    print(f"Execution time:  {elapsed:.5f}s")
    print(f"Status:          {data.get('status')}")
    print(f"Conversational:  {data.get('conversational_explanation', '')[:100]}...")
    assert data.get("status") == "success"
    print("[PASSED] POST /ask-remediation Passed!")

def test_fallback_endpoint():
    print("\n--- TEST 4: Fallback for Unknown Questions ---")
    start = time.perf_counter()
    response = client.post("/chat", json={"question": "What is the recipe for chocolate cake?"})
    elapsed = time.perf_counter() - start

    assert response.status_code == 200
    data = response.json()
    print(f"Execution time:  {elapsed:.5f}s")
    print(f"Answer snippet:  {data.get('answer')[:120]}...")
    assert "could not find this exact topic" in data.get("answer", "")
    assert data.get("generated_by") == "local_knowledge_engine"
    print("[PASSED] Fallback Test Passed!")

if __name__ == "__main__":
    test_chat_endpoint()
    test_explain_finding_endpoint()
    test_ask_remediation_endpoint()
    test_fallback_endpoint()
    print("\n========================================================")
    print("ALL FASTAPI ENDPOINT TESTS PASSED SUCCESSFULLY!")
    print("========================================================\n")
