"""
Test suite for Hybrid RAG Knowledge Retrieval & AI Assistant
"""
import time
import logging
from unittest.mock import MagicMock
from backend.agents.conversational_code_assistant import ConversationalCodeAssistant

logging.basicConfig(level=logging.INFO)

PROMPT_TEST_QUESTIONS = [
    ("What is phone?", True),
    ("What is SQL Injection?", False),
    ("Why is eval() dangerous?", False),
    ("What is PEP 8?", False),
    ("What is AST analysis?", False),
    ("How do I fix hardcoded credentials?", False),
    ("What is football?", True),
]

EXPECTED_UNSUPPORTED_ANSWER = (
    "I can help with SentinelAI topics such as secure coding, "
    "OWASP, PEP 8, AST analysis, vulnerabilities, code analysis, "
    "and remediation. I don't have relevant SentinelAI knowledge for this question."
)


def run_tests():
    assistant = ConversationalCodeAssistant()
    # Mock Ollama service for deterministic test execution
    assistant.ollama_service.generate_chat = MagicMock(side_effect=lambda system_prompt, user_prompt, history=None: (
        f"Grounded response for prompt topic: {user_prompt[:50]}..."
    ))

    print("\n========================================================")
    print("RUNNING SENTINELAI HYBRID RAG KNOWLEDGE TESTS")
    print("========================================================\n")

    total_time = 0.0

    # Mock findings to ensure unsupported questions DO NOT trigger finding context
    mock_findings = [
        {"line": 14, "severity": "Critical", "issue": "Hardcoded Password", "explanation": "Exposed key in variable"}
    ]

    for i, (q, is_unsupported) in enumerate(PROMPT_TEST_QUESTIONS, start=1):
        start = time.perf_counter()
        res = assistant.ask(question=q, optional_findings=mock_findings if not is_unsupported else None)
        elapsed = time.perf_counter() - start
        total_time += elapsed

        print(f"[{i}/7] Question: '{q}'")
        print(f"      Completed in: {elapsed:.5f}s")
        print(f"      Generated By: {res.get('generated_by')}")
        print(f"      Source:       {res.get('source')}")
        print(f"      Answer Snippet:")
        print(f"      {res.get('answer', '')[:140]}...\n")

        assert res.get("generated_by") == "ollama"
        assert res.get("source") == "ollama_rag"

        if is_unsupported:
            assert res.get("answer") == EXPECTED_UNSUPPORTED_ANSWER, (
                f"Mismatch for unsupported question '{q}'. Got: {res.get('answer')}"
            )
            assert "Hardcoded Password" not in res.get("answer"), (
                f"Finding context illegally attached to unsupported question '{q}'!"
            )
        else:
            assert res.get("answer") != EXPECTED_UNSUPPORTED_ANSWER, (
                f"Valid domain question '{q}' was mistakenly rejected as unsupported!"
            )

    print("========================================================")
    print(f"ALL 7 TESTS PASSED SUCCESSFULLY IN {total_time:.5f}s TOTAL!")
    print("========================================================\n")

if __name__ == "__main__":
    run_tests()
